const schoolCodes = [
  { SchoolName: "Royal College, Colombo", SchoolCode: "RC001", Team: "A" },
  { SchoolName: "Ananda College, Colombo", SchoolCode: "AC002", Team: "B" },
  { SchoolName: "Musaeus College, Colombo", SchoolCode: "MC003", Team: "C" },
  { SchoolName: "Trinity College, Kandy", SchoolCode: "TC004", Team: "A" },
  { SchoolName: "Hillwood College, Kandy", SchoolCode: "HC005", Team: "B" },
  {
    SchoolName: "St. Thomas' College, Mt. Lavinia",
    SchoolCode: "ST006",
    Team: "A",
  },
  { SchoolName: "Ladies' College, Colombo", SchoolCode: "LC007", Team: "C" },
  {
    SchoolName: "Maliyadeva College, Kurunegala",
    SchoolCode: "MD008",
    Team: "A",
  },
  { SchoolName: "Rahula College, Matara", SchoolCode: "RC009", Team: "B" },
  { SchoolName: "Dharmaraja College, Kandy", SchoolCode: "DR010", Team: "C" },
  {
    SchoolName: "St. Anne's College, Kurunegala",
    SchoolCode: "SA011",
    Team: "A",
  },
  { SchoolName: "Visakha Vidyalaya, Colombo", SchoolCode: "VV012", Team: "B" },
  {
    SchoolName: "Jaffna Hindu College, Jaffna",
    SchoolCode: "JH013",
    Team: "C",
  },
  {
    SchoolName: "St. Peter's College, Colombo",
    SchoolCode: "SP014",
    Team: "A",
  },
  { SchoolName: "Richmond College, Galle", SchoolCode: "RC015", Team: "B" },
  {
    SchoolName: "St. Joseph's College, Colombo",
    SchoolCode: "SJ016",
    Team: "C",
  },
  { SchoolName: "Wesley College, Colombo", SchoolCode: "WC017", Team: "A" },
  { SchoolName: "Kingswood College, Kandy", SchoolCode: "KC018", Team: "B" },
  {
    SchoolName: "St. Anthony's College, Kandy",
    SchoolCode: "SA019",
    Team: "C",
  },
  {
    SchoolName: "Sri Sumangala College, Panadura",
    SchoolCode: "SS020",
    Team: "A",
  },
  {
    SchoolName: "Sri Jayewardenepura Maha Vidyalaya, Kotte",
    SchoolCode: "SJ021",
    Team: "B",
  },
  { SchoolName: "Nalanda College, Colombo", SchoolCode: "NC022", Team: "C" },
  {
    SchoolName: "Holy Family Convent, Colombo",
    SchoolCode: "HF023",
    Team: "A",
  },
  {
    SchoolName: "Sirimavo Bandaranaike Vidyalaya, Colombo",
    SchoolCode: "SB024",
    Team: "B",
  },
  {
    SchoolName: "St. Sebastian's College, Moratuwa",
    SchoolCode: "SS025",
    Team: "C",
  },
];

const results = [
  {
    SchoolName: "Royal College, Colombo",
    TeamCode: "RC-COLOMBO-A",
    Marks: 99,
    Place: "1st Place",
  },
  {
    SchoolName: "Ananda College, Colombo",
    TeamCode: "AC-COLOMBO-B",
    Marks: 98,
    Place: "2nd Place",
  },
  {
    SchoolName: "Musaeus College, Colombo",
    TeamCode: "MC-COLOMBO-C",
    Marks: 97,
    Place: "3rd Place",
  },
  {
    SchoolName: "Trinity College, Kandy",
    TeamCode: "TC-KANDY-A",
    Marks: 96,
    Place: "4th Place",
  },
  {
    SchoolName: "Hillwood College, Kandy",
    TeamCode: "HC-KANDY-B",
    Marks: 95,
    Place: "5th Place",
  },
  {
    SchoolName: "St. Thomas' College, Mt. Lavinia",
    TeamCode: "ST-MTL-A",
    Marks: 94,
    Place: "6th Place",
  },
  {
    SchoolName: "Ladies' College, Colombo",
    TeamCode: "LC-COLOMBO-C",
    Marks: 93,
    Place: "7th Place",
  },
  {
    SchoolName: "Maliyadeva College, Kurunegala",
    TeamCode: "MD-KURU-A",
    Marks: 92,
    Place: "8th Place",
  },
  {
    SchoolName: "Rahula College, Matara",
    TeamCode: "RC-MATARA-B",
    Marks: 91,
    Place: "9th Place",
  },
  {
    SchoolName: "Dharmaraja College, Kandy",
    TeamCode: "DR-KANDY-C",
    Marks: 90,
    Place: "10th Place",
  },
  {
    SchoolName: "St. Anne's College, Kurunegala",
    TeamCode: "SA-KURU-A",
    Marks: 89,
    Place: "11th Place",
  },
  {
    SchoolName: "Visakha Vidyalaya, Colombo",
    TeamCode: "VV-COLOMBO-B",
    Marks: 88,
    Place: "12th Place",
  },
  {
    SchoolName: "Jaffna Hindu College, Jaffna",
    TeamCode: "JH-JAFFNA-C",
    Marks: 87,
    Place: "13th Place",
  },
  {
    SchoolName: "St. Peter's College, Colombo",
    TeamCode: "SP-COLOMBO-A",
    Marks: 86,
    Place: "14th Place",
  },
  {
    SchoolName: "Richmond College, Galle",
    TeamCode: "RC-GALLE-B",
    Marks: 85,
    Place: "15th Place",
  },
  {
    SchoolName: "St. Joseph's College, Colombo",
    TeamCode: "SJ-COLOMBO-C",
    Marks: 84,
    Place: "16th Place",
  },
  {
    SchoolName: "Wesley College, Colombo",
    TeamCode: "WC-COLOMBO-A",
    Marks: 83,
    Place: "17th Place",
  },
  {
    SchoolName: "Kingswood College, Kandy",
    TeamCode: "KC-KANDY-B",
    Marks: 82,
    Place: "18th Place",
  },
  {
    SchoolName: "St. Anthony's College, Kandy",
    TeamCode: "SA-KANDY-C",
    Marks: 81,
    Place: "19th Place",
  },
  {
    SchoolName: "Sri Sumangala College, Panadura",
    TeamCode: "SS-PANA-A",
    Marks: 80,
    Place: "20th Place",
  },
  {
    SchoolName: "Sri Jayewardenepura Maha Vidyalaya, Kotte",
    TeamCode: "SJ-KOTTE-B",
    Marks: 79,
    Place: "21st Place",
  },
  {
    SchoolName: "Nalanda College, Colombo",
    TeamCode: "NC-COLOMBO-C",
    Marks: 78,
    Place: "22nd Place",
  },
  {
    SchoolName: "Holy Family Convent, Colombo",
    TeamCode: "HF-COLOMBO-A",
    Marks: 77,
    Place: "23rd Place",
  },
  {
    SchoolName: "Sirimavo Bandaranaike Vidyalaya, Colombo",
    TeamCode: "SB-COLOMBO-B",
    Marks: 76,
    Place: "24th Place",
  },
  {
    SchoolName: "St. Sebastian's College, Moratuwa",
    TeamCode: "SS-MORAT-C",
    Marks: 75,
    Place: "25th Place",
  },
];
